const IMAGES = {
    advertising: require('./images/advertising.png'),
    architectural_design: require('./images/architectural_design.png'),
    arts_and_crafts: require('./images/arts_and_crafts.png'),
    web_design: require('./images/web_design.png'),
    graphic_design: require('./images/graphic_design.png'),
    interior_design: require('./images/interior_design.png'),
    fashion: require('./images/fashion.png'),
    communications: require('./images/communications.png'),
    photography_fundamentals: require('./images/photography_fundamentals.png'),
    potraits: require('./images/potraits.png'),
    video_design: require('./images/video_design.png'),
    commercial_photography: require('./images/commercial_photography.png'),
    food_and_beverage: require('./images/food_and_beverage.png'),
    travel: require('./images/travel.png'),
    gaming: require('./images/gaming.png'),
    pet_care_and_training: require('./images/pet_care_and_training.png'),
    fitness: require('./images/fitness.png'),
    general_health: require('./images/general_health.png'),
    sports: require('./images/sports.png'),
    nutrition: require('./images/nutrition.png'),
    yoga: require('./images/yoga.png'),
    dance: require('./images/dance.png'),
    meditation: require('./images/meditation.png'),
    dieting: require('./images/dieting.png'),
    eductional_development: require('./images/eductional_development.png'),
    teaching_tool: require('./images/teaching_tool.png'),
    instruments: require('./images/instruments.png'),
    production: require('./images/production.png'),
    music_fundamentals: require('./images/music_fundamentals.png'),
    vocal: require('./images/vocal.png'),
    english: require('./images/english.png'),
    spanish: require('./images/spanish.png'),
    german: require('./images/german.png'),
    french: require('./images/french.png'),
    russian: require('./images/russian.png'),
    latin: require('./images/latin.png'),
    databases: require('./images/databases.png'),
    web_development: require('./images/web_development.png'),
    programming_languages: require('./images/programming_languages.png'),
    ecommerce: require('./images/ecommerce.png'),
    digital_marketing: require('./images/digital_marketing.png'),
    social_media_marketing: require('./images/social_media_marketing.png'),
    branding: require('./images/branding.png'),
    public_relations: require('./images/public_relations.png'),
    advertising: require('./images/advertising.png'),
    content_marketing: require('./images/content_marketing.png'),
    finance: require('./images/finance.png'),
    entrepreneurship: require('./images/entrepreneurship.png'),
    sales: require('./images/sales.png'),
    management: require('./images/management.png'),
    strategy: require('./images/strategy.png'),
    real_estate: require('./images/real_estate.png'),
    other: require('./images/other.png'),
    health_and_fitness: require('./images/health_and_fitness.png'),
    business: require('./images/business.png'),
    design: require('./images/design.png'),
    photography: require('./images/photography.png'),
    lifestyle: require('./images/lifestyle.png'),
    teacher_training: require('./images/teacher_training.png'),
    music: require('./images/music.png'),
    language: require('./images/language.png'),
    development: require('./images/development.png'),
    marketing: require('./images/marketing.png'),
}

getImage = (name: String) => {
    return IMAGES[name]
}

export default getImage